"""Models Migration

Revision ID: 37d100651ff6
Revises: 
Create Date: 2025-05-04 20:00:28.743701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d100651ff6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('interests', sa.String(), nullable=True),
    sa.Column('geohash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_geohash'), 'users', ['geohash'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actor_target_status', 'user_activities', ['actor_id', 'target_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_activities_actor_id'), 'user_activities', ['actor_id'], unique=False)
    op.create_index(op.f('ix_user_activities_status'), 'user_activities', ['status'], unique=False)
    op.create_index(op.f('ix_user_activities_target_id'), 'user_activities', ['target_id'], unique=False)
    op.create_index(op.f('ix_user_activities_timestamp'), 'user_activities', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activities_timestamp'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_target_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_status'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_actor_id'), table_name='user_activities')
    op.drop_index('ix_actor_target_status', table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_geohash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
